name: Run on PR Comment

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - synchronize

jobs:
  run_on_comment:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test') }}
    name: "Run job"
    runs-on: ["ubuntu-latest"]
    permissions:
      checks: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.checks.create({
              name: "Tests"
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'in_progress',
              external_id: '62',
              head_sha: context.sha
            })

      - name: "build"
        run: |
          cargo build

      - name: "test"
        run: |
          cargo test

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: '62',
              status: 'completed',
              head_sha: context.sha
              conclusion: 'success'
            })
