name: Run on PR Comment

on:
  issue_comment:
    types:
      - created

jobs:
  run_on_comment:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test') }}
    name: "Run job"
    runs-on: ["ubuntu-latest"]
    permissions:
      checks: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: LouisBrunner/checks-action@v1.6.1
        id: start_checkrun
        if: always()
        with:
          token: ${{ github.token }}
          name: Run Tests
          status: in_progress

      - name: "build"
        run: |
          cargo build

      - name: "test"
        run: |
          cargo test

      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          check_id: ${{ steps.start_checkrun.outputs.check_id }}
          token: ${{ github.token }}
          name: Run Tests
          conclusion: ${{ job.status }}
