name: Run on PR Comment

on:
  issue_comment:
    types:
      - created

jobs:
  run_on_comment:
    if: ${{ github.event.issue.pull_request }}
    name: "Run job"
    runs-on: ["ubuntu-latest"]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: "build"
        run: |
          cargo build

      - name: "test"
        if: contains(github.event.comment.body, '/test')
        run: |
          cargo test
